- name : provisioning instance for apache
  hosts: localhost
  connection: local
  remote_user: ec2-user
  gather_facts: false
  roles:
    - ec2_apache

- name: Launch instance
  ec2:
     key_name: "{{ keypair }}"
     group: "{{ sg-0859fee5dfe21cc97 }}"
     instance_type: "{{ t2.micro }}"
     image: "{{ ami-0c322300a1dd5dc79 }}"
     wait: true
     region: "{{ us-east-1 }}"
     vpc_subnet-id: subnet-16898019
     assign_public_ip: yes
  register: ec2

- name: Adding a new instance
  add_host: hostname={{ item.public_ip }} groupname=launched
  with_items: ec2.instances

- name: waiting for ssh to spin up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 state=started
  with_items: ec2.instances

- name: install Apache
  hosts: launched
  remote_user: ec2-user
  roles:
    - apache

